### ISSUE TITLE
need ddnet.tw/status support

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet7#14]
https://github.com/ddnet/ddnet-scripts/blob/master/servers/scripts/teeworlds.py probably doesn't support the 64 player packets for 0.7, right?

**Comment by fokkonaut** [comment]
why shouldnt it?

**Comment by def-** [comment]
They use the same packet format? Didn't check.

**Comment by Learath2** [comment]
I'm not sure whether the server is even capable of reporting all 64 players, I'm doubtful but I'll take a look.

It sends all 64 clients but the format isn't the same. It's all packed into a single packet. I'm not sure how that works out given it can get larger then the max payload size, which is why I thought we were splitting it up.

**Comment by def-** [comment]
Tried it, definitely not showing any servers: https://ddnet.tw/status/7.html

**Comment by def-** [comment]
I will use the tw_api.py included in TW0.7 instead.

**Comment by def-** [comment]
Done.
