### ISSUE TITLE
Spectators aren't allowed to vote (/pause)

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet7#46]
Paused players should be able to call a vote.

**Comment by fokkonaut** [comment]
This is clientside: https://github.com/teeworlds/teeworlds/blob/7e7b13699a2583526a300dec62bd6bf34dffbef1/src/game/client/components/menus_ingame.cpp#L734

**Comment by fokkonaut** [comment]
I have an idea, maybe I can hack something here. Will see when I get home...

**Comment by fokkonaut** [comment]
Okay, so there is no real way to go around this. I made it so the server sends a team change to spectators, thats because we want to nicely be able to use the spectator mode tee selector. If not sending this message we can still move around in pause and we are able to call a vote, but we cant use the tee selector anymore. So this will need to wait until we have an official client
